### ISSUE TITLE
Edit the site to reflect that the Coalition government is no longer in power

### ISSUE THREAD

**Issue by tduck973564** [mdavis-xyz/mdavis.xyz#38]
The site says that the government 'has been in power for over 8 years' and that it is the 'current' government, which should be updated now that they aren't in anymore.

**Comment by mdavis-xyz** [comment]
Fixed, thanks

**Comment by tduck973564** [comment]
You missed a bit 😅
![Screenshot_20220711-000210_Chrome~2](https://user-images.githubusercontent.com/71878148/178148179-f4178cd6-f49a-40d2-b32a-a72ba4ab0b50.png)
